// Importing core modules
const os = require('os');       // To access OS-related info
const fs = require('fs');       // To interact with the file system
const crypto = require('crypto'); // To generate random values for encryption

// Get OS-related info using the 'os' module
console.log("Operating System Platform:", os.platform());    // Logs the OS platform (e.g., 'linux', 'win32')
console.log("Total Memory in Bytes:", os.totalmem());        // Logs the total memory available in the system

// Writing to a file using the 'fs' module
fs.writeFileSync('test.txt', 'Hello, this is a test file created using the fs module!'); 
console.log("File 'test.txt' has been created.");

// Generate a random value using the 'crypto' module
const randomValue = crypto.randomBytes(16).toString('hex');
console.log("Random Value generated by crypto module:", randomValue);  // Logs a random value
